// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	GetAdminInfoMessage
	AdminInfoResponse
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAdminInfoMessage struct {
	TargetAdminName string `protobuf:"bytes,1,opt,name=target_admin_name,json=targetAdminName" json:"target_admin_name,omitempty"`
}

func (m *GetAdminInfoMessage) Reset()                    { *m = GetAdminInfoMessage{} }
func (m *GetAdminInfoMessage) String() string            { return proto.CompactTextString(m) }
func (*GetAdminInfoMessage) ProtoMessage()               {}
func (*GetAdminInfoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetAdminInfoMessage) GetTargetAdminName() string {
	if m != nil {
		return m.TargetAdminName
	}
	return ""
}

type AdminInfoResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  string `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
}

func (m *AdminInfoResponse) Reset()                    { *m = AdminInfoResponse{} }
func (m *AdminInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*AdminInfoResponse) ProtoMessage()               {}
func (*AdminInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AdminInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminInfoResponse) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAdminInfoMessage)(nil), "GetAdminInfoMessage")
	proto.RegisterType((*AdminInfoResponse)(nil), "AdminInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Admin service

type AdminClient interface {
	GetAdminInfo(ctx context.Context, in *GetAdminInfoMessage, opts ...grpc.CallOption) (*AdminInfoResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetAdminInfo(ctx context.Context, in *GetAdminInfoMessage, opts ...grpc.CallOption) (*AdminInfoResponse, error) {
	out := new(AdminInfoResponse)
	err := grpc.Invoke(ctx, "/Admin/GetAdminInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	GetAdminInfo(context.Context, *GetAdminInfoMessage) (*AdminInfoResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_GetAdminInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminInfoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdminInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin/GetAdminInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdminInfo(ctx, req.(*GetAdminInfoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminInfo",
			Handler:    _Admin_GetAdminInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe4, 0x12, 0x76, 0x4f, 0x2d, 0x71, 0x4c, 0xc9,
	0xcd, 0xcc, 0xf3, 0xcc, 0x4b, 0xcb, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0xd2, 0xe2,
	0x12, 0x2c, 0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x89, 0x4f, 0x04, 0x49, 0xc5, 0xe7, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xf1, 0x43, 0x24, 0xc0, 0x5a, 0xfc, 0x12, 0x73, 0x53,
	0x95, 0x2c, 0xb9, 0x04, 0xe1, 0xfa, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84,
	0xb8, 0x58, 0x90, 0xf4, 0x80, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x60,
	0x21, 0x10, 0xd3, 0xc8, 0x99, 0x8b, 0x15, 0xac, 0x55, 0xc8, 0x8a, 0x8b, 0x07, 0xd9, 0x19, 0x42,
	0x22, 0x7a, 0x58, 0x5c, 0x25, 0x25, 0xa4, 0x87, 0x61, 0x91, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x27,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xe4, 0xec, 0x60, 0xd7, 0x00, 0x00, 0x00,
}
